version : "3"
services:


  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    expose:
      - 27017
    command: mongod --port 27017 --bind_ip 0.0.0.0
    restart: "on-failure"


  app:
    build: "./app"
    depends_on:
      - mongodb
    restart: "on-failure"
